# Entri_Assignment_7

In [12]:
import numpy as np
import pandas as pd

In [8]:
# Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
array = np.arange(1,11)
array
array1 = array.reshape(2,5)
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
x = np.arange(1,21)
extracted_elements = x[5:15]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [16]:
# Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series  = pd.Series(data)
series['pears']=4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [18]:
# Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Ella', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 30, 22, 28, 26, 29, 31, 27, 24, 23],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)
print(df)

      name  age  gender
0    Alice   25  Female
1      Bob   30    Male
2  Charlie   22    Male
3    David   28    Male
4     Ella   26  Female
5    Frank   29    Male
6    Grace   31  Female
7   Hannah   27  Female
8      Ian   24    Male
9     Jack   23    Male


In [20]:
# Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print(df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Ella   26  Female     Manager
5    Frank   29    Male     Analyst
6    Grace   31  Female  Programmer
7   Hannah   27  Female     Manager
8      Ian   24    Male     Analyst
9     Jack   23    Male  Programmer


In [22]:
# Select the rows of the dataframe where the age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]
print(filtered_df)

    name  age  gender  occupation
1    Bob   30    Male     Manager
6  Grace   31  Female  Programmer


In [24]:
# Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv('dataframe.csv', index=False)
# Read the CSV file into a new DataFrame
new_df = pd.read_csv('dataframe.csv')
print(new_df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   28    Male  Programmer
4     Ella   26  Female     Manager
5    Frank   29    Male     Analyst
6    Grace   31  Female  Programmer
7   Hannah   27  Female     Manager
8      Ian   24    Male     Analyst
9     Jack   23    Male  Programmer
